baseURL = '/'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh'
enableEmoji = true
enableGitInfo = true

theme = "lotusdocs"

[languages]
  [languages.zh]
    title = "装修手记"
    languageName = "中文"
    weight = 10

[module]
  [module.hugoVersion]
    extended = true
    min = "0.140.0"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  google_fonts = [
    ["Inter", "300, 400, 600, 700"],
    ["Fira Code", "500, 700"]
  ]

  sans_serif_font = "Inter"
  secondary_font  = "Inter"
  mono_font       = "Fira Code"

  [params.footer]
    copyright = "© :YEAR: 装修手记"

  [params.social]
    github = ""
    twitter = ""

  [params.docs]
    title = "装修手记"
    darkMode = true
    prism = true
    prismTheme = "lotusdocs"
    sidebarIcons = true
    breadcrumbs = true
    backToTop = true
    toc = true
    tocMobile = true
    scrollSpy = true
    descriptions = true
    titleIcon = true

  [params.flexsearch]
    enabled = true

[menu]
[[menu.primary]]
    name  = "装修日志"
    url = "/"
    identifier = "home"
    weight = 10
